let number1 = 5;
let number2 = 6;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
let charge = 20;
let payment = 10;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
let tests = 70;
let assignments = 50;
let final = 90;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Stephanie';
const lastName = 'Rowan';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
let ph = 10;
const isAsidic = ph < 7;
console.log(isAsidic);
console.log(typeof isAsidic);
let numberOfSolders = 250;
const isSparta = numberOfSolders == 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
